#!/usr/bin/sh

# (c) 2015 Gord Smith <rjs.linux@gmail.com>
# service for Arch Linux
# distributed under GPL License

if [ -f /usr/lib/rjs-utils/core.sh ]; then
	source /usr/lib/rjs-utils/core.sh
else
	echo
	echo "ERROR: Unable to find /usr/lib/rjs-utils/core.sh"
	echo " -* make sure you have rjs-utils package installed"
	echo
	exit 1
fi

if [ "$1" = "" -o "$1" = "--help" ]; then
	echo
	eecho "  ${WHITE}Usage: ${GREEN}${0}${YELLOW} service-name${ENDCOLOR} ${CYAN}action${ENDCOLOR}"
	eecho
	eecho "  ${WHITE}Actions:"
	echo
	eecho "  ${CYAN}  start    ${ENDCOLOR} -${WHITE} Start the service."
	eecho "  ${CYAN}  stop     ${ENDCOLOR} -${WHITE} Stop the service."
	eecho "  ${CYAN}  status   ${ENDCOLOR} -${WHITE} Status of the service (if it supports querying)."
	eecho "  ${CYAN}  restart  ${ENDCOLOR} -${WHITE} Stop and start again the service."
	eecho "  ${CYAN}  add      ${ENDCOLOR} -${WHITE} Adds a new service for management by systemd."
	eecho "  ${CYAN}  del      ${ENDCOLOR} -${WHITE} Removes a service from systemd management."
	eecho "  ${ENDCOLOR}"
	exit 0
fi

if [ "$1" = "--version" ]; then
	echo
	eecho "service 0.1"
	echo
	eecho "Copyright (c) 2015 by Gord Smith <rjs.linux@gmail.com>"
	echo
	eecho "This is free software; see the source for copying conditions.  There is NO"
	eecho "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
	echo
	exit 0

fi

service=$1.service
if [ "$2" = "add" ]; then
	runasroot /usr/bin/systemctl enable $service
elif [ "$2" = "del" ]; then
	runasroot /usr/bin/systemctl disable $service
elif [ "$2" = "list" ]; then
	if /usr/bin/systemctl is-enabled $service; then
		echo enabled
	else
		echo disabled
	fi
else
	runasroot /usr/bin/systemctl $2 $service
fi
