#!/bin/sh
set -e

# include core.sh functions
if [ -f /usr/lib/rjs-utils/core.sh ]; then
	source /usr/lib/rjs-utils/core.sh
else
	echo
	echo " -* ERROR: Unable to find /usr/lib/rjs-utils.core.sh"
	echo " -* make sure you have rjs-utils package installed"
	echo
	exit 1
fi

runasroot /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg "$@"
